const games=[
 {title:'賽博浪人',genre:'動作冒險',cover:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=85',accent:'#58f6c1',online:'12.4K',progress:64,tag:'熱門'},
 {title:'幻境邊界',genre:'MMORPG',cover:'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=900&q=85',accent:'#b7ff69',online:'8.7K',progress:0,tag:'新作'},
 {title:'極速：夜城',genre:'競速',cover:'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=900&q=85',accent:'#ffbd59',online:'5.2K',progress:28,tag:'推薦'},
 {title:'星際流亡者',genre:'科幻射擊',cover:'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=900&q=85',accent:'#6ce5ff',online:'9.1K',progress:0,tag:'熱門'},
 {title:'王國餘燼',genre:'角色扮演',cover:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85',accent:'#fa8c73',online:'3.8K',progress:0,tag:'精選'}];
const icon=(name)=>`<span class="material">${name}</span>`;
document.querySelector('#root').innerHTML=`<div class="app">
<aside class="sidebar"><div class="logo"><span class="logo-mark">N</span><span>NOVA</span></div><nav>${[['⌂','探索'],['▣','遊戲庫'],['⇩','下載'],['♙','社群']].map(([i,x])=>`<button class="${x==='探索'?'active':''}"><b>${i}</b><span>${x}</span>${x==='下載'?'<i>2</i>':''}</button>`).join('')}</nav><div class="side-bottom"><button>⚙ <span>設定</span></button><div class="mini-profile"><div class="avatar">K</div><div><strong>KAI.CHEN</strong><small><span></span> 線上</small></div><b>›</b></div></div></aside>
<main><header><label class="search">⌕<input aria-label="搜尋遊戲" placeholder="搜尋遊戲、類型或玩家..."/><kbd>⌘ K</kbd></label><div class="header-actions"><div class="server">◒ 台北節點 <strong>12 ms</strong></div><button class="icon-btn">♢<span></span></button><div class="header-avatar">K</div>⌄</div></header>
<section class="hero"><img src="https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1800&q=90" alt="霓虹電競場景"><div class="hero-shade"></div><div class="hero-copy"><div class="eyebrow">✦ 本週精選</div><h1>無限疆界<br><em>就在指尖</em></h1><p>史詩級開放世界 MMORPG。與千名玩家一同探索失落文明，<br>你的每個選擇，都將改寫這個世界。</p><div class="hero-meta"><span>MMORPG</span><span>開放世界</span><span class="rating">★ 4.9</span><small>32.6K 人在線</small></div><div class="hero-buttons"><button class="play-main" data-play="無限疆界">▶ 立即遊玩</button><button class="detail">查看詳情 ›</button></div></div><div class="hero-pagination"><button>‹</button><span class="on"></span><span></span><span></span><button>›</button></div><div class="cloud-badge">◒<div><strong>雲端串流</strong><small>無需下載 · 即點即玩</small></div></div></section>
<section class="content"><div class="section-head"><div><p class="kicker">為你精選</p><h2>探索遊戲宇宙</h2></div><button>查看全部 ›</button></div><div class="filters">${['全部遊戲','MMORPG','動作冒險','科幻射擊','競速','角色扮演'].map((x,i)=>`<button class="${i?'':'selected'}">${x}</button>`).join('')}</div><div class="game-grid"></div></section>
<footer><span>© 2026 NOVA CLOUD</span><p>遊戲不受限，世界無邊界。</p><div><a>隱私權</a><a>服務條款</a><a>支援中心</a></div></footer></main></div><div class="modal-root"></div>`;

let genre='全部遊戲', query='', liked=new Set([0]);
function render(){const list=games.filter(g=>(genre==='全部遊戲'||g.genre===genre)&&g.title.includes(query));document.querySelector('.game-grid').innerHTML=list.length?list.map((g)=>{const i=games.indexOf(g);return `<article class="game-card" style="--accent:${g.accent}"><div class="game-art"><img src="${g.cover}" alt="${g.title}"><span class="tag">${g.tag}</span><button class="heart ${liked.has(i)?'liked':''}" data-like="${i}" aria-label="加入收藏">${liked.has(i)?'♥':'♡'}</button><button class="card-play" data-game="${i}">▶</button></div><div class="game-info"><div><h3>${g.title}</h3><p>${g.genre}</p></div><span class="online"><i></i>${g.online}</span></div>${g.progress?`<div class="progress"><div><span style="width:${g.progress}%"></span></div><small>◷ 上次遊玩進度 ${g.progress}%</small></div>`:''}</article>`}).join(''):`<div class="empty">找不到符合「${query}」的遊戲</div>`}
render();
document.addEventListener('click',e=>{const filter=e.target.closest('.filters button');if(filter){genre=filter.textContent;document.querySelectorAll('.filters button').forEach(x=>x.classList.toggle('selected',x===filter));render()}const like=e.target.closest('[data-like]');if(like){const i=+like.dataset.like;liked.has(i)?liked.delete(i):liked.add(i);render()}const card=e.target.closest('[data-game]');const play=e.target.closest('[data-play]');if(card||play){const g=card?games[+card.dataset.game]:{title:'無限疆界',cover:document.querySelector('.hero>img').src};document.querySelector('.modal-root').innerHTML=`<div class="player-modal"><div class="player-window" style="background-image:url('${g.cover}')"><button class="close">×</button><div class="player-ui"><span>◒ 1080P · 60 FPS</span><div class="launch"><div class="loader">▣</div><h2>正在啟動 ${g.title}</h2><p>連接台北雲端主機...</p></div><div class="controls">♬ <span>NOVA CLOUD PLAY</span><strong>12 ms</strong></div></div></div></div>`}if(e.target.closest('.close'))document.querySelector('.modal-root').innerHTML='';});
document.querySelector('.search input').addEventListener('input',e=>{query=e.target.value.trim();render()});
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
